### ISSUE TITLE
Use standard file naming and layout

### ISSUE THREAD

**Issue by yasuiniko** [panahiparham/ml-experiment-definition#13]
Some reorganization that I think would help
- [ ] ~~`./src/ml_experiment/...` instead of `./ml_experiment/...`
This is the default that is expected by pytest and setuptools.~~
- [ ] `part_definition.py` instead of `PartDefinition.py`.
This avoids confusion between module names and class names — does `tests/test_PartDefinition.py` test `PartDefinition.py`, or the `PartDefinition` class?
    ```python
    from ml_experiment import PartDefinition

    my_part_definition = PartDefinition.PartDefinition()
    ```

**Comment by panahiparham** [comment]
@andnp what do you think?

**Comment by andnp** [comment]
Strong agree on the second. Unsure about the first. I _believe_ that standard practice for python libraries is that source code is located in `<library_name>/*.py`

**Comment by yasuiniko** [comment]
That works for me! I removed the task about the folder structure to focus on the renaming.
