### ISSUE TITLE
Can't install package with pip install

### ISSUE THREAD

**Issue by yasuiniko** [panahiparham/ml-experiment-definition#21]
To reproduce:

```bash
python -m venv .venv
source .venv/bin/activate
pip install -e '.[dev]'  # or pip install '.[dev]', pip install .
```

Error:
<img width="1184" alt="Screenshot 2024-10-29 at 18 06 10" src="https://github.com/user-attachments/assets/6b3f3f56-016d-481f-ac76-eb6767ee7caf">

**Comment by panahiparham** [comment]
On my system with python3.11 all three variants of the commits just works!
