### ISSUE TITLE
UX: scheduler doesn't tell users where to save results

### ISSUE THREAD

**Issue by yasuiniko** [panahiparham/ml-experiment-definition#23]
The following assumes this layout:

- ml-experiment-definition
  - experiments
    - exp_name
      - my_experiment.py
  - results
    - exp_name
      - metadata.db

Right now we want the results of `my_experiment.py` to be stored under `results/exp_name/`, and we are trusting users to write `my_experiment.py` from scratch. It's very easy right now for users to save their results in some other path.

I think scheduler should pass `--results-path=results/exp_name/` to `my_experiment.py` by default, so that users are forced to be aware of the intended location for experiment results.

**Comment by andnp** [comment]
Yup totally agreed here.
